version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
      - 8001:443
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
    ports: 
      - 5432:5432
    volumes:
      - ./SQL/:/var/lib/postgresql/data